### ISSUE TITLE
Decide whether to make this repository public.

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conference#13]
We’re currently tracking this planning work in a private github repo. Shoud we move the repo to the ipfs org and make it public?

**Comment by flyingzumwalt** [comment]
This repository is now public. @skylarnorris do you want me to make the readme specifically call out the fact that the dates aren't fully set in stone?

**Comment by skylarnorris** [comment]
Nope, they're set - we have options! So, dates are for sure what they're
going to be for the event as outlined in this repo.


--------------
"Dance like no one is watching. Encrypt like everyone is."
