### ISSUE TITLE
Create Application Forms for attending the Developer Meetings and set a timeline for Applications

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conference#4]
- **IPFS Dev Meeting** [Edit Application Form](https://docs.google.com/forms/d/16E6RWwFHcL68X2sXwh1iMEP1c_KMxqHztNGGVRAzwLo/edit) Live form: https://goo.gl/forms/sVRjrW1CA61FTwl12
- **libp2p Dev Meeting** [Edit Application Form](https://docs.google.com/forms/d/1SIQkzrLIhOLVEuC-yuPAbBvo44oMh-_y_vJJP1S4WM8/edit) Live form: https://goo.gl/forms/8YpFQ7D00s5gC3hw2
- **IPFSConf pre-registration** [Edit pre-registration form](https://docs.google.com/forms/d/1eEFYKybkMjx1Q_m64BgFFFJ_pSOFu8kGMZgH_fK3-jo/edit), Live form: https://goo.gl/forms/0Pu6VZzG8pRAmrrv2

All the responses/applications are in the [conference applications spreadsheet](https://docs.google.com/spreadsheets/d/1MDDa4gPw-BglZfAYAhpdoNKnPAX-5q980PmNsXa47cE/edit#gid=0)

Create **separate** Application Forms for IPFS Dev Meeting and libp2p Dev Meeting. Anyone can apply to attend. We will then review the applications and invite people based on their level of involvement in the projects. People who want to attend both Dev Meetings must apply for both (a lot of people who do belong at the IPFS Dev Meeting don't have enough context to contribute to conversations at the libp2p Dev Meeting)

Note: Decision about eligibility to attend should be need-blind, meaning that we shouldn't reject people based on whether they can fund their attendance. 

- [x] Choose a timeline for Applications, Acceptance, Registration, etc.
- [x] Create Application Form for IPFS Dev Meeting
- [x] Create Application Form for libp2p Dev Meeting

The forms should get info on:
- Which project(s) the applicant works on, and the name of that project in the IPFS/libp2p User Registry
- How many people want to come from that project
- Which working groups they want to contribute to
- Do you need financial assistance in order to be able to attend the Dev Meeting? If so, do you need assistance with...
    - Reducing or Waiving Registration Fee
    - Accommodations
    - Travel Assistance
- _What else should we ask? Please comment._

**Comment by flyingzumwalt** [comment]
I made this repo public, so we've soft-launched applications as of today. Still need to set a timeline and a plan for reviewing the applications.

**Comment by flyingzumwalt** [comment]
The libp2p dev meeting application has the ipfs areas of work — need to replace them with libp2p-specific options. @mgoelzer could you put together a list?

**Comment by mgoelzer** [comment]
Yes, libp2p form is updated & ready to ship.

**Comment by mgoelzer** [comment]
I just marked both applications as closed with a note encouraging them to pre-register for conf.
