### ISSUE TITLE
Create a Website for IPFS Developers Meeting, libp2p Developers Meeting and IPFS Conf

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conference#6]
Create a Website for all three events: IPFS Developers Meeting, libp2p Developers Meeting and IPFS Conf

- [x] Find a firm to make the website (@skylarnorris)
- [x] ~Have @akrych put together a logo and basic visual branding for the events (@skylarnorris)~ --> discussion moved to [issue 33](https://github.com/ipfs/conference/issues/33)
- [ ] ~Plan the content of the website (@flyingzumwalt)~ --> discussion moved to [issue 34](https://github.com/ipfs/conference/issues/34)
- [ ] Ship it.

**Comment by meiqimichelle** [comment]
I believe all of the tasks in the issue are now either closed or moved to their own issues, as noted. Closing, but please re-open if I've missed something.
